[package]
name = "example_server"
version = "0.0.1"
edition = "2024"

[dependencies]
once_cell = "1.20.2"
tokio = { version = "1.45.1", features = ["full"] }
rustmine_lib = { path = "../rustmine_lib" }
rustmine_server = { path = "../rustmine_server" }