[package]
name = "codegen"
version = "0.0.1"
edition = "2024"

[dependencies]
serde_json = { version =  "1.0.140"}
serde = { version = "1.0.219", features = ["derive"]}
toml = "0.8.20"
itertools = "0.14.0"